# Generated by Django 4.2.5 on 2023-09-19 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_chat_id_chat_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='api_key',
            new_name='apikey',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nick_name',
            new_name='nickName',
        ),
    ]
