# Generated by Django 4.2.5 on 2023-09-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_api_key_user_apikey_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='apikey',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nickName',
            new_name='nick_name',
        ),
    ]
