# Generated by Django 4.2.5 on 2023-09-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_apikey_user_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chatName',
            field=models.CharField(default='New Chat', max_length=50),
        ),
    ]
