# Generated by Django 4.2.5 on 2023-09-25 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chat_chatname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chatName',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_name',
            field=models.CharField(default='New Chat', max_length=50),
        ),
        migrations.AddField(
            model_name='chat',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 14, 2, 23, 809708, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='message',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 14, 2, 23, 809227, tzinfo=datetime.timezone.utc)),
        ),
    ]
