# Generated by Django 4.2.5 on 2023-09-25 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_chat_create_time_alter_user_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 14, 9, 8, 734559, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 14, 9, 8, 734134, tzinfo=datetime.timezone.utc)),
        ),
    ]
