# Generated by Django 4.2.5 on 2023-09-28 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_message_sender_alter_chat_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 7, 17, 9, 270003, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='chat',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 7, 17, 9, 269992, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 28, 7, 17, 9, 269669, tzinfo=datetime.timezone.utc)),
        ),
    ]
