# Generated by Django 4.2.5 on 2023-11-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_chat_create_time_alter_chat_update_time_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(),
        ),
    ]
