# Generated by Django 4.2.5 on 2023-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_apikey_key_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlobField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_data', models.TextField(blank=True, db_column='data')),
            ],
        ),
    ]
