# Generated by Django 4.2.5 on 2023-11-23 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_blobfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='blobfield',
            name='user',
            field=models.OneToOneField(default=101010101, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
