# Generated by Django 4.2.5 on 2023-11-24 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_blobfield__data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blobfield',
            old_name='_data',
            new_name='data',
        ),
    ]
