---
API_URLS:
  BASE_URL: http://127.0.0.1:8000/api
  MESSAGES_URL: http://127.0.0.1:8000/api/messages
  CHATS_URL: http://127.0.0.1:8000/api/chats
  USERS_URL: http://127.0.0.1:8000/api/users
BASE_INFERENCE_URL: http://127.0.0.1:8000/api/inference
